INSERT INTO universite (ad, link, sehirid) VALUES
('ABANT İZZET BAYSAL ÜNİVERSİTESİ', 'https://www.ibu.edu.tr/Website/Default.aspx', 14),
('ABDULLAH GÜL ÜNİVERSİTESİ', 'https://w3.agu.edu.tr/', 38),
('ACIBADEM MEHMET ALİ AYDINLAR ÜNİVERSİTESİ', 'https://www.acibadem.edu.tr/', 34),
('ADANA BİLİM VE TEKNOLOJİ ÜNİVERSİTESİ', 'https://www.atu.edu.tr/#!/', 1),
('ADIYAMAN ÜNİVERSİTESİ', 'https://adiyaman.edu.tr/', 2),
('ADNAN MENDERES ÜNİVERSİTESİ', 'https://www.adu.edu.tr/', 9),
('AFYON KOCATEPE ÜNİVERSİTESİ', 'https://aku.edu.tr/', 3),
('AĞRI İBRAHİM ÇEÇEN ÜNİVERSİTESİ', 'https://www.agri.edu.tr/', 4),
('AHİ EVRAN ÜNİVERSİTESİ', 'https://www.ahievran.edu.tr/', 40),
('AKDENİZ KARPAZ ÜNİVERSİTESİ', 'https://akun.edu.tr/', 82),
('AKDENİZ ÜNİVERSİTESİ', 'https://www.akdeniz.edu.tr/', 7),
('AKSARAY ÜNİVERSİTESİ', 'https://www.aksaray.edu.tr/', 68),
('ALANYA ALAADDİN KEYKUBAT ÜNİVERSİTESİ', 'https://www.alanya.edu.tr/', 7),
('ALANYA HAMDULLAH EMİN PAŞA ÜNİVERSİTESİ', 'https://www.alanyauniversity.edu.tr/', 7),
('ALTINBAŞ ÜNİVERSİTESİ', 'https://altinbas.edu.tr/', 34),
('AMASYA ÜNİVERSİTESİ', 'https://www.amasya.edu.tr/', 5),
('ANADOLU ÜNİVERSİTESİ', 'https://www.anadolu.edu.tr/', 26),
('ANKARA SOSYAL BİLİMLER ÜNİVERSİTESİ', 'https://www.asbu.edu.tr/tr', 6),
('ANKARA ÜNİVERSİTESİ', 'https://www.ankara.edu.tr/', 6),
('ANKARA YILDIRIM BEYAZIT ÜNİVERSİTESİ', 'https://aybu.edu.tr/', 6),
('ANTALYA AKEV ÜNİVERSİTESİ', 'https://www.belek.edu.tr/', 7),
('ANTALYA BİLİM ÜNİVERSİTESİ', 'https://antalya.edu.tr/tr', 7),
('ARDAHAN ÜNİVERSİTESİ', 'https://www.ardahan.edu.tr/', 75),
('ARTVİN ÇORUH ÜNİVERSİTESİ', 'https://www.artvin.edu.tr/', 8),
('ATAŞEHİR ADIGÜZEL MESLEK YÜKSEKOKULU', 'https://www.adiguzel.edu.tr/', 34),
('ATATÜRK ÜNİVERSİTESİ', 'https://www.atauni.edu.tr/', 25),
('ATILIM ÜNİVERSİTESİ', 'https://www.atilim.edu.tr/tr', 6),
('AVRASYA ÜNİVERSİTESİ', 'https://avrasya.edu.tr/', 61),
('AVRUPA MESLEK YÜKSEKOKULU', 'https://kocaelisaglik.edu.tr/avrupamyo/', 34),
('BAHÇEŞEHİR ÜNİVERSİTESİ', 'https://bau.edu.tr/', 34),
('BALIKESİR ÜNİVERSİTESİ', 'https://www.balikesir.edu.tr/', 10),
('BANDIRMA ONYEDİ EYLÜL ÜNİVERSİTESİ', 'https://www.bandirma.edu.tr/', 10),
('BARTIN ÜNİVERSİTESİ', 'https://w3.bartin.edu.tr/', 74),
('BAŞKENT ÜNİVERSİTESİ', 'https://www.baskent.edu.tr/tr/', 6),
('BATMAN ÜNİVERSİTESİ', 'https://batman.edu.tr/', 72),
('BAYBURT ÜNİVERSİTESİ', 'https://bayburt.edu.tr/', 69),
('BEYKENT ÜNİVERSİTESİ', 'https://www.beykent.edu.tr/', 34),
('BEYKOZ ÜNİVERSİTESİ', 'https://www.beykoz.edu.tr/', 34),
('BEZM-İ ÂLEM VAKIF ÜNİVERSİTESİ', 'https://bezmialem.edu.tr/tr/Sayfalar/anasayfa.aspx', 34),
('BİLECİK ŞEYH EDEBALİ ÜNİVERSİTESİ', 'https://www.bilecik.edu.tr/', 11),
('BİNGÖL ÜNİVERSİTESİ', 'https://www.bingol.edu.tr/tr', 12),
('BİRUNİ ÜNİVERSİTESİ', 'https://www.biruni.edu.tr/', 34),
('BİTLİS EREN ÜNİVERSİTESİ', 'https://www.beu.edu.tr/', 13),
('BOĞAZİÇİ ÜNİVERSİTESİ', 'https://bogazici.edu.tr/', 34),
('BOZOK ÜNİVERSİTESİ', 'https://www.bozok.edu.tr/', 66),
('BURSA TEKNİK ÜNİVERSİTESİ', 'https://www.btu.edu.tr/', 16),
('BÜLENT ECEVİT ÜNİVERSİTESİ', 'https://w3.beun.edu.tr/', 67),
('CUMHURİYET ÜNİVERSİTESİ', 'https://www.cumhuriyet.edu.tr/', 58),
('ÇAĞ ÜNİVERSİTESİ', 'https://www.cag.edu.tr/tr', 33),
('ÇANAKKALE ONSEKİZ MART ÜNİVERSİTESİ', 'https://www.comu.edu.tr/', 17),
('ÇANKAYA ÜNİVERSİTESİ', 'https://www.cankaya.edu.tr/', 6),
('ÇANKIRI KARATEKİN ÜNİVERSİTESİ', 'https://www.karatekin.edu.tr/', 18),
('ÇUKUROVA ÜNİVERSİTESİ', 'https://www.cu.edu.tr/', 1),
('DİCLE ÜNİVERSİTESİ', 'https://www.dicle.edu.tr/', 21),
('DOĞU AKDENİZ ÜNİVERSİTESİ', 'https://www.emu.edu.tr/tr', 82),
('DOĞUŞ ÜNİVERSİTESİ', 'https://www.dogus.edu.tr/', 34),
('DOKUZ EYLÜL ÜNİVERSİTESİ', 'https://www.deu.edu.tr/', 35),
('DUMLUPINAR ÜNİVERSİTESİ', 'https://www.dpu.edu.tr/', 43),
('DÜZCE ÜNİVERSİTESİ', 'https://duzce.edu.tr/', 81),
('EGE ÜNİVERSİTESİ', 'https://ege.edu.tr/tr-0/anasayfa.html', 35),
('ERCİYES ÜNİVERSİTESİ', 'https://www.erciyes.edu.tr/', 38),
('ERZİNCAN ÜNİVERSİTESİ', 'https://ebyu.edu.tr/', 24),
('ERZURUM TEKNİK ÜNİVERSİTESİ', 'https://erzurum.edu.tr/#gsc.tab=0', 25),
('ESKİŞEHİR OSMANGAZİ ÜNİVERSİTESİ', 'https://www.ogu.edu.tr/', 26),
('FARUK SARAÇ TASARIM MESLEK YÜKSEKOKULU', 'https://www.issb.edu.tr/', 16),
('FATİH SULTAN MEHMET VAKIF ÜNİVERSİTESİ', 'https://www.fsm.edu.tr/', 34),
('FIRAT ÜNİVERSİTESİ', 'https://www.firat.edu.tr/tr', 23),
('GALATASARAY ÜNİVERSİTESİ', 'https://gsu.edu.tr/tr', 34),
('GAZİ ÜNİVERSİTESİ', 'https://gazi.edu.tr/', 6),
('GAZİANTEP ÜNİVERSİTESİ', 'https://www.gaziantep.edu.tr/', 27),
('GAZİOSMANPAŞA ÜNİVERSİTESİ', 'https://www.gop.edu.tr/', 60),
('GEBZE TEKNİK ÜNİVERSİTESİ', 'https://www.gtu.edu.tr/', 41),
('GİRESUN ÜNİVERSİTESİ', 'https://www.giresun.edu.tr/', 28),
('GİRNE AMERİKAN ÜNİVERSİTESİ', 'https://www.gau.edu.tr/', 82),
('GİRNE ÜNİVERSİTESİ', 'https://kyrenia.edu.tr/', 82),
('GÜMÜŞHANE ÜNİVERSİTESİ', 'https://www.gumushane.edu.tr/', 29),
('HACETTEPE ÜNİVERSİTESİ', 'https://www.hacettepe.edu.tr/', 6),
('HAKKARİ ÜNİVERSİTESİ', 'https://www.hakkari.edu.tr/', 30),
('HALİÇ ÜNİVERSİTESİ', 'https://halic.edu.tr/tr', 34),
('HARRAN ÜNİVERSİTESİ', 'https://www.harran.edu.tr/', 63),
('HASAN KALYONCU ÜNİVERSİTESİ', 'https://www.hku.edu.tr/', 27),
('HİTİT ÜNİVERSİTESİ', 'https://www.hitit.edu.tr/', 19),
('IĞDIR ÜNİVERSİTESİ', 'https://www.igdir.edu.tr/home', 76),
('IŞIK ÜNİVERSİTESİ', 'https://www.isikun.edu.tr/', 34),
('İBN HALDUN ÜNİVERSİTESİ', 'https://www.ihu.edu.tr/tr', 34),
('İHSAN DOĞRAMACI BİLKENT ÜNİVERSİTESİ', 'https://w3.bilkent.edu.tr/www/', 6),
('İNÖNÜ ÜNİVERSİTESİ', 'https://www.inonu.edu.tr/', 44),
('İSKENDERUN TEKNİK ÜNİVERSİTESİ', 'https://iste.edu.tr/', 31),
('İSTANBUL 29 MAYIS ÜNİVERSİTESİ', 'https://www.29mayis.edu.tr/tr/', 34),
('İSTANBUL AREL ÜNİVERSİTESİ', 'https://arel.edu.tr/', 34),
('İSTANBUL AYDIN ÜNİVERSİTESİ', 'https://www.aydin.edu.tr/tr-tr/Pages/default.aspx', 34),
('İSTANBUL AYVANSARAY ÜNİVERSİTESİ', 'https://www.topkapi.edu.tr/', 34),
('İSTANBUL BİLGİ ÜNİVERSİTESİ', 'https://www.bilgi.edu.tr/tr/', 34),
('İSTANBUL ESENYURT ÜNİVERSİTESİ', 'https://www.esenyurt.edu.tr/', 34),
('İSTANBUL GEDİK ÜNİVERSİTESİ', 'https://www.gedik.edu.tr/', 34),
('İSTANBUL GELİŞİM ÜNİVERSİTESİ', 'https://www.gelisim.edu.tr/tr/gelisim-anasayfa', 34),
('İSTANBUL KAVRAM MESLEK YÜKSEKOKULU', 'https://www.kavram.edu.tr/', 34),
('İSTANBUL KENT ÜNİVERSİTESİ', 'https://www.kent.edu.tr/', 34),
('İSTANBUL KÜLTÜR ÜNİVERSİTESİ', 'https://www.iku.edu.tr/', 34),
('İSTANBUL MEDENİYET ÜNİVERSİTESİ', 'https://medeniyet.edu.tr/tr', 34),
('İSTANBUL MEDİPOL ÜNİVERSİTESİ', 'https://www.medipol.edu.tr/', 34),
('İSTANBUL RUMELİ ÜNİVERSİTESİ', 'https://rumeli.edu.tr/', 34),
('İSTANBUL SABAHATTİN ZAİM ÜNİVERSİTESİ', 'https://www.izu.edu.tr/', 34),
('İSTANBUL ŞEHİR ÜNİVERSİTESİ', 'https://tr.wikipedia.org/wiki/%C4%B0stanbul_%C5%9Eehir_%C3%9Cniversitesi', 34),
('İSTANBUL ŞİŞLİ MESLEK YÜKSEKOKULU', 'https://www.sisli.edu.tr/', 34),
('İSTANBUL TEKNİK ÜNİVERSİTESİ', 'https://itu.edu.tr/', 34),
('İSTANBUL TİCARET ÜNİVERSİTESİ', 'https://ticaret.edu.tr/', 34),
('İSTANBUL ÜNİVERSİTESİ', 'https://www.istanbul.edu.tr/tr/_', 34),
('İSTANBUL YENİ YÜZYIL ÜNİVERSİTESİ', 'https://www.yeniyuzyil.edu.tr/', 34),
('İSTİNYE ÜNİVERSİTESİ', 'https://www.istinye.edu.tr/tr', 34),
('İZMİR DEMOKRASİ ÜNİVERSİTESİ', 'https://idu.edu.tr/', 35),
('İZMİR EKONOMİ ÜNİVERSİTESİ', 'https://www.ieu.edu.tr/tr', 35),
('İZMİR KATİP ÇELEBİ ÜNİVERSİTESİ', 'https://ikcu.edu.tr/', 35),
('İZMİR YÜKSEK TEKNOLOJİ ENSTİTÜSÜ', 'https://iyte.edu.tr/', 35),
('KADİR HAS ÜNİVERSİTESİ', 'https://www.khas.edu.tr/', 34),
('KAFKAS ÜNİVERSİTESİ', 'https://www.kafkas.edu.tr/', 36),
('KAHRAMANMARAŞ SÜTÇÜ İMAM ÜNİVERSİTESİ', 'https://www.ksu.edu.tr/', 46),
('KAPADOKYA ÜNİVERSİTESİ', 'https://kapadokya.edu.tr/', 50),
('KARABÜK ÜNİVERSİTESİ', 'https://www.karabuk.edu.tr/', 78),
('KARADENİZ TEKNİK ÜNİVERSİTESİ', 'https://www.ktu.edu.tr/', 61),
('KARAMANOĞLU MEHMETBEY ÜNİVERSİTESİ', 'https://www.kmu.edu.tr/', 70),
('KASTAMONU ÜNİVERSİTESİ', 'https://kastamonu.edu.tr/index.php/tr/', 37),
('KIBRIS AMERİKAN ÜNİVERSİTESİ', 'https://auc.edu.tr/', 82),
('KIBRIS İLİM ÜNİVERSİTESİ', 'https://cau.edu.tr/', 82),
('KIBRIS SOSYAL BİLİMLER ÜNİVERSİTESİ', 'https://kktc.asbu.edu.tr/tr', 82),
('KIRIKKALE ÜNİVERSİTESİ', 'https://kku.edu.tr/Anasayfa', 71),
('KIRKLARELİ ÜNİVERSİTESİ', 'https://www.klu.edu.tr/', 39),
('KİLİS 7 ARALIK ÜNİVERSİTESİ', 'https://kilis.edu.tr/', 79),
('KOCAELİ ÜNİVERSİTESİ', 'https://www.kocaeli.edu.tr/', 41),
('KOÇ ÜNİVERSİTESİ', 'https://www.ku.edu.tr/', 34),
('KONYA GIDA VE TARIM ÜNİVERSİTESİ', 'https://www.gidatarim.edu.tr/', 42),
('KTO KARATAY ÜNİVERSİTESİ', 'https://www.karatay.edu.tr/tr/', 42),
('LEFKE AVRUPA ÜNİVERSİTESİ', 'https://www.eul.edu.tr/tr/', 82),
('MALTEPE ÜNİVERSİTESİ', 'https://www.maltepe.edu.tr/', 34),
('MANİSA CELAL BAYAR ÜNİVERSİTESİ', 'https://www.mcbu.edu.tr/', 45),
('MARDİN ARTUKLU ÜNİVERSİTESİ', 'https://www.artuklu.edu.tr/', 47),
('MARMARA ÜNİVERSİTESİ', 'https://www.marmara.edu.tr/', 34),
('MEF ÜNİVERSİTESİ', 'https://www.mef.edu.tr/tr', 34),
('MEHMET AKİF ERSOY ÜNİVERSİTESİ', 'https://www.mehmetakif.edu.tr/tr', 15),
('MERSİN ÜNİVERSİTESİ', 'https://www.mersin.edu.tr/', 33),
('MİLLİ SAVUNMA ÜNİVERSİTESİ', 'https://www.msu.edu.tr/', 34),
('MİMAR SİNAN GÜZEL SANATLAR ÜNİVERSİTESİ', 'https://msgsu.edu.tr/', 34),
('MUĞLA SITKI KOÇMAN ÜNİVERSİTESİ', 'https://www.mu.edu.tr/tr', 48),
('MUNZUR ÜNİVERSİTESİ', 'https://www.munzur.edu.tr/', 62),
('MUSTAFA KEMAL ÜNİVERSİTESİ', 'https://www.mku.edu.tr/', 31),
('MUŞ ALPARSLAN ÜNİVERSİTESİ', 'https://www.alparslan.edu.tr/tr', 49),
('NAMIK KEMAL ÜNİVERSİTESİ', 'https://www.nku.edu.tr/', 59),
('NECMETTİN ERBAKAN ÜNİVERSİTESİ', 'https://www.erbakan.edu.tr/', 42),
('NEVŞEHİR HACI BEKTAŞ VELİ ÜNİVERSİTESİ', 'https://www.nevsehir.edu.tr/', 50),
('NİĞDE ÖMER HALİSDEMİR ÜNİVERSİTESİ', 'https://www.ohu.edu.tr/', 51),
('NİŞANTAŞI ÜNİVERSİTESİ', 'https://www.nisantasi.edu.tr/', 34),
('NUH NACİ YAZGAN ÜNİVERSİTESİ', 'https://www.nny.edu.tr/', 38),
('OKAN ÜNİVERSİTESİ', 'https://www.okan.edu.tr/', 34),
('ONDOKUZ MAYIS ÜNİVERSİTESİ', 'https://www.omu.edu.tr/tr', 55),
('ORDU ÜNİVERSİTESİ', 'https://www.odu.edu.tr/', 52),
('ORTA DOĞU TEKNİK ÜNİVERSİTESİ', 'https://www.metu.edu.tr/tr', 6),
('OSMANİYE KORKUT ATA ÜNİVERSİTESİ', 'https://www.osmaniye.edu.tr/', 80),
('ÖZYEĞİN ÜNİVERSİTESİ', 'https://www.ozyegin.edu.tr/tr', 34),
('PAMUKKALE ÜNİVERSİTESİ', 'https://www.pau.edu.tr/', 20),
('PİRİ REİS ÜNİVERSİTESİ', 'https://pirireis.edu.tr/', 34),
('RECEP TAYYİP ERDOĞAN ÜNİVERSİTESİ', 'https://erdogan.edu.tr/Website/Default.aspx', 53),
('SABANCI ÜNİVERSİTESİ', 'https://sabanciuniv.edu/tr', 34),
('SAĞLIK BİLİMLERİ ÜNİVERSİTESİ', 'https://sbu.edu.tr/', 34),
('SAKARYA ÜNİVERSİTESİ', 'https://www.sakarya.edu.tr/', 54),
('SANKO ÜNİVERSİTESİ', 'https://www.sanko.edu.tr/', 27),
('SELÇUK ÜNİVERSİTESİ', 'https://selcuk.edu.tr/', 42),
('SİİRT ÜNİVERSİTESİ', 'https://siirt.edu.tr/', 56),
('SİNOP ÜNİVERSİTESİ', 'https://sinop.edu.tr/', 57),
('SÜLEYMAN DEMİREL ÜNİVERSİTESİ', 'https://w3.sdu.edu.tr/', 32),
('ŞIRNAK ÜNİVERSİTESİ', 'https://www.sirnak.edu.tr/tr', 73),
('TED ÜNİVERSİTESİ', 'https://www.tedu.edu.tr/', 6),
('TOBB EKONOMİ VE TEKNOLOJİ ÜNİVERSİTESİ', 'https://www.etu.edu.tr/tr', 6),
('TOROS ÜNİVERSİTESİ', 'https://toros.edu.tr/', 33),
('TRAKYA ÜNİVERSİTESİ', 'https://www.trakya.edu.tr/', 22),
('TÜRK HAVA KURUMU ÜNİVERSİTESİ', 'https://www.thk.edu.tr/', 6),
('TÜRK-ALMAN ÜNİVERSİTESİ', 'https://www.tau.edu.tr/', 34),
('UFUK ÜNİVERSİTESİ', 'https://www.ufuk.edu.tr/', 6),
('ULUDAĞ ÜNİVERSİTESİ', 'https://www.uludag.edu.tr/', 16),
('ULUSLAR ARASI KIBRIS ÜNİVERSİTESİ', 'https://ciu.edu.tr/tr', 82),
('UŞAK ÜNİVERSİTESİ', 'https://www.usak.edu.tr/', 64),
('ÜSKÜDAR ÜNİVERSİTESİ', 'https://uskudar.edu.tr/', 34),
('YAKINDOĞU ÜNİVERSİTESİ', 'https://neu.edu.tr/', 82),
('YALOVA ÜNİVERSİTESİ', 'https://www.yalova.edu.tr/', 77),
('YAŞAR ÜNİVERSİTESİ', 'https://www.yasar.edu.tr/', 35),
('YEDİTEPE ÜNİVERSİTESİ', 'https://yeditepe.edu.tr/tr', 34),
('YILDIZ TEKNİK ÜNİVERSİTESİ', 'https://www.yildiz.edu.tr/', 34),
('YÜKSEK İHTİSAS ÜNİVERSİTESİ', 'https://yuksekihtisasuniversitesi.edu.tr/', 6),
('YÜZÜNCÜ YIL ÜNİVERSİTESİ', 'https://www.yyu.edu.tr/', 65),
('İSTANBUL BİLİM ÜNİVERSİTESİ', 'https://demiroglu.bilim.edu.tr/', 34);